/// Flutter icons ExpenseTrackerIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ExpenseTrackerIcons
///      fonts:
///       - asset: fonts/ExpenseTrackerIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ExpenseTrackerIcons {
  ExpenseTrackerIcons._();

  static const _kFontFam = 'ExpenseTrackerIcons';
  static const String? _kFontPkg = null;

  static const IconData arrow_up = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_down = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_up = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
